### ISSUE TITLE
Generate the parity bits

### ISSUE THREAD

**Issue by surajkadapa** [surajkadapa/hamming_code_1#1]
The data bits are given, but the parity haven't been generated. Generate the parity bits

**Comment by ManushriJ** [comment]
can i get assigned

**Comment by surajkadapa** [comment]
@ManushriJ Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
@guptabros Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by KunalMaverick** [comment]
is this still open?

**Comment by ManushriJ** [comment]
can i get reassigned to this?

**Comment by surajkadapa** [comment]
@ManushriJ Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by User-LazySloth** [comment]
Hey there! Could you please assign this to me!

**Comment by surajkadapa** [comment]
@User-LazySloth Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by User-LazySloth** [comment]
@surajkadapa Resolve the given issue, please do check it

**Comment by surajkadapa** [comment]
This issue has been closed.
